version: '3'
services:
  
  geoserver:
    image: 'geotekne/geoserver:lime-buster-2.16.2'
    hostname: geoserver
    env_file:
      - ./geoserver.env
    environment:
      - STABLE_EXTENSIONS=css-plugin,feature-pregeneralized-plugin
      - GEOSERVER_DATA_DIR=/var/local/geoserver
    ports:
      - "8080:8080"
    volumes:
      - './data/geoserver/data_dir/:/var/local/geoserver'
    depends_on:
      - postgis
    restart: on-failure

  wmsclient:
    image: 'nginx:1.21.3-alpine'
    hostname: wmsclient
    volumes:
      - './data/nginx/html:/usr/share/nginx/html'
    ports:
      - "80:80"
    restart: on-failure

  postgis:
    image: 'kartoza/postgis:12.1'
    hostname: postgis
    container_name: osm-geoserver-postgis_postgis
    env_file:
      - ./postgis.env
    volumes:
      - 'pgdata:/var/lib/postgresql'
    ports:
      - "5432:5432"
    restart: on-failure

volumes: 
     pgdata:

